name: Generate Travel Page

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - main
    paths:
      - 'images/**'
      - '.github/workflows/generate-travel-page.yml'
      - 'scripts/generate_travel_page.py'

jobs:
  generate-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          
      - name: Generate travel page
        run: python scripts/generate_travel_page.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add travel.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update travel page [skip ci]" && git push) 